name: Raw CI/CD for Node.js

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/Deva-2002/devops2-BE.git .
          git checkout main

      - name: Install Node.js manually
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm install

      
